url: "sel-columbia.github.io"
name: >
  Sustainable Engineering Lab at Columbia
  University
description: >
  Engineering for tough developing world
  issues.

# Site settings
title: Sustainable Engineering Lab
email: your-email@columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/


# Build settings
markdown: kramdown

exclude: [path]
  
# Navigation
navigation:
- text: about
  url: /about/
- text: projects 
  url: /projects/
- text: publications
  url: /publications/
- text: tools
  url: /products-tools/
- text: blog
  url: /blog/
- text: jobs
  url: /jobs/
