url: "sel-columbia.github.io"
name: >
  Sustainable Engineering Lab at Columbia
  University
description: >
  Engineering for tough developing world
  issues.

# Site settings
title: "Sustainable Engineering Lab @ Columbia University"
email: your-email@columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/

gems:
  - jekyll-redirect-from

permalink: /:title/

# Build settings
markdown: kramdown

exclude: [path, vendor]

collections:
  team:
    output: true
    permalink: /team/:title/

# Navigation
navigation:
- text: about
  url: /about/
- text: projects
  url: /projects/
- text: publications
  url: /publications/
- text: tools
  url: /products-tools/
- text: blog
  url: /blog/
- text: jobs
  url: /jobs/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: "Untagged"
  -
    scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: "page"

# Configurations for Prose
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  #ignore: ['file_a.html', '_config.yml']
  #site:
  #media: ""
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          options:
            - name: "Infrastructure"
              value: Infrastructure
            - name: "Energy Planning"
              value: energy planning
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
